# Generated by Django 5.2.1 on 2025-06-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='upcoming_book_covers/')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
