# Generated by Django 5.2.1 on 2025-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingbook',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
